# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mabuhay
tagline:          The Ruby GUI Framework
url:              http://mattmeng.github.io/mabuhay
paginate:         1
baseurl:          /
author:
  name:           Matt Meng
  url:            http://mattmeng.github.io/
  email:          mattmeng@gmail.com
markdown:         redcarpet

# Custom vars
version:          0.0.0
github:
  repo:           https://github.com/mattmeng/mabuhay
